add the 2nd version of calc
igorstupnik/for_git pull request #2
Opened 2024-11-09 03:44 UTC by igorstupnik

Here is a second version of calc to review

2024-11-09 04:34 UTC, eugenenazirov requested changes
Отлично. Теперь PR абсолютно корректный, я прекрасно вижу все изменения.

На консультации нужно будет поднять тему работы с ветками чуть глубже, т.к. она практически не освещается в курсе Хекслета. Если я забуду - напомни, пожалуйста.

По калькулятору, все супер, базовый функционал реализован. На данном этапе нужно озаботиться обработкой ошибок, т.к. сейчас мы вообще не валидируем ввод пользователя и спокойно ломаемся на любой абракадабре которую он может ввести.

2024-11-11 05:28 UTC, eugenenazirov requested changes
Молодец, что добавил обработку ошибок, но её тоже стоит доработать.

То, что отмечено nit - необязательные замечания, которые можно поправить позже на своё усмотрение, подробнее [читай здесь](https://einsmanntech.medium.com/how-to-nitpick-on-code-reviews-with-empathy-d6cb8e670ca4).

2024-11-11 05:28 UTC, eugenenazirov commented on my_calc_v2.go
> -	}
Не понял этот маневр. Речь шла о том, чтобы вернуть ошибку явно, а не удалять код проверяющий ошибочный кейс.

2024-11-11 05:28 UTC, eugenenazirov commented on my_calc_v2.go
> +	_, err1 := fmt.Scanln(&b)
Так делать не нужно. Переменную `err` стоит переиспользовать, так как старое её содержимое уже не актуально. Если там был не `nil`, ты бы уже не дошел до этой строчки.

2024-11-11 05:28 UTC, eugenenazirov commented on my_calc_v2.go
> +		os.Exit(0)
os.Exit() это дурной тон. Если у тебя будет более сложное приложение, оно просто не успеет корректно завершить работу, потому что os.Exit прибьёт его моментально. 
В бэкенд-приложениях это вообще запрещено делать, так как там мы работаем с внешними ресурсами, и надо будет наоборот делать graceful shutdown, чтобы высвободить их. 

Достаточно просто `return`.

2024-11-11 05:28 UTC, eugenenazirov commented on my_calc_v2.go
> +		fmt.Println("Ошибка: введено не число.")
Как ты понял, что введено не число? Тут же нет никакой явной проверки.

2024-11-11 05:28 UTC, eugenenazirov commented on my_calc_v2.go
> +	if operator != "+" && operator != "-" && operator != "*" && operator != "/" {
Nit: в будущем стоит вынести такие операции в отдельную функцию-валидатор. А может быть использовать какой-нибудь внешний пакет для валидации.

2024-11-11 05:28 UTC, eugenenazirov commented on my_calc_v2.go
> +		//fmt.Println("Неизвестный оператор")
Nit: Закомментированный код лучше не оставлять.

2024-11-11 05:28 UTC, eugenenazirov commented on my_calc_v2.go
> +		}
По-моему ты зря перенес проверку с нулем сюда. Еще раз напоминаю, что стоит просто заставить функцию divide возвращать ошибку явно, и все должно встать на свои места.

2024-11-12 06:01 UTC, igorstupnik commented on my_calc_v2.go
> +		fmt.Println("Ошибка: введено не число.")
выше я объявляю **_а_** и **_в_** как **_float64_**, т.о. если ввод не соответсвует этому будет выходить **_err_**

2024-11-12 06:10 UTC, igorstupnik commented on my_calc_v2.go
> -	}
поскольку это у меня было в отдельном коммите, я сделал revert именно всего что касалось деления на ноль

2024-11-12 06:21 UTC, igorstupnik commented on my_calc_v2.go
> +	_, err1 := fmt.Scanln(&b)
когда я использую второй раз переменную **_err_** через присваивание **_:=_** возникает ошибка **_NoNewVar_**. Чтобы этого избежать второй раз без инициализации просто **_=_** Изменю и залью отдельным коммитом

2024-11-12 06:36 UTC, igorstupnik commented on my_calc_v2.go
> +		os.Exit(0)
отдельным коммитом изменил  **_os.Exit(0)_** на r**_eturn 0, 0, ""_**

2024-11-12 06:42 UTC, igorstupnik commented on my_calc_v2.go
> +		//fmt.Println("Неизвестный оператор")
удалил строчку **_fmt.Println("Неизвестный оператор")_** отдельным коммитом

2024-11-12 10:43 UTC, eugenenazirov commented on my_calc_v2.go
> +		fmt.Println("Ошибка: введено не число.")
Хорошо, валидно. Я бы предпочел более явно сканировать в `string` и затем парсить в `float` с помощью пакета `strconv`, но это уже вкусовщина.

2024-11-12 10:44 UTC, eugenenazirov commented on my_calc_v2.go
> +	_, err1 := fmt.Scanln(&b)
Да, об этом и речь. Инициализация не нужна здесь, т.к. надо переиспользовать имеющуюся переменную

2024-11-12 10:46 UTC, eugenenazirov commented on my_calc_v2.go
> -	}
Если я правильно понял, просто делаешь `result, err := divide(a, b)`. Если есть хоть одна новая переменная, не объявленная ранее то сработает корректно.

2024-11-12 10:47 UTC, eugenenazirov requested changes

2024-11-12 10:47 UTC, eugenenazirov commented on my_calc_v2.go
> +		return 0, errors.New("деление на ноль")
Текст ошибок должен быть исключительно англоязычным.

2024-11-12 10:47 UTC, eugenenazirov commented on my_calc_v2.go
> +func divide(a, b float64) (float64, error) {
Вот так супер! Лайк

2024-11-12 14:33 UTC, eugenenazirov approved these changes
Текущий этап можно считать завершенным. Ставлю аппрув.

Отдельный лайк за то, как работаешь с коммитами, они у тебя достаточно атомарные и хорошо названы. Добавлю лишь то, что есть также стандарт именования коммитов с большой буквы. Его не все придерживаются, и это вообще не критично, но все равно полезно знать.

2024-11-12 14:33 UTC, eugenenazirov commented on my_calc_v2.go
> +func getInput() (float64, float64, string, error) {
Правила хорошего тона говорят, что когда у тебя больше трех возвращаемых значений, стоит задуматься над тем, чтобы объединить эти значения в структуру и оперировать ей. В терминах чистой архитектуры это может быть доменная модель или Entity, а если данные специфичны для конкретного слоя и используются только в нём, то это скорее будет DTO. 

В данном случае DTO пока делать смысла не имеет, с этим познакомимся позже. А пока рекомендую изучить разницу между Entity и DTO и прикрутить сюда структуру Entity для удобства и последующего переиспользования.

2024-11-12 14:33 UTC, eugenenazirov commented on my_calc_v2.go
> +		return 0, 0, "", fmt.Errorf("unknown operator %s", operator)
Лайк за форматированный текст ошибки.

2024-11-13 09:48 UTC, merged