Layer verification
igorstupnik/for_git pull request #3
Opened 2024-11-13 12:30 UTC by igorstupnik

Hi there!
Could you please look at the calculator in the three layers: Main, Presentation, and Business

2024-11-15 17:56 UTC, eugenenazirov requested changes
Уже выглядит очень чисто и хорошо. Проблемы вижу только в нейминге пакетов.

Пока не пахнет go-project-layout, может быть ты еще не успел его посмотреть, а может не нашел. На всякий случай оставлю ссылки здесь:
1. [Самый старый и общеизвестный материал (доступен на русском)](https://github.com/golang-standards/project-layout)
2. [Официальная статейка гугла, более свежая и актуальная (только на английском)](https://go.dev/doc/modules/layout)

2024-11-15 17:56 UTC, eugenenazirov commented on my_calc_v2.go
Nit: Как будто можно было просто оставить этот вариант в другой ветке. Ну да ладно)

2024-11-15 17:56 UTC, eugenenazirov commented on presentation/input.go
> +//presentation/input.go
Nit: а это зачем? Просто лишнее осталось? Лучше убрать

2024-11-15 17:56 UTC, eugenenazirov commented on presentation/input.go
> +package presentation
Ты верно понял идею представления, но в коммерческих приложениях представления называются `view`. В данном случае можно не дублировать названия из MVC, а просто назвать пакет `console` или `cli`, чтобы подчеркнуть что мы работаем с командной строкой здесь.

2024-11-15 17:56 UTC, eugenenazirov commented on presentation/input.go
> +	if operator != "+" && operator != "-" && operator != "*" && operator != "/" {
Такую штучку вынести бы в отдельную функцию-валидатор, чтобы не выглядело так громоздко.

2024-11-15 17:56 UTC, eugenenazirov commented on presentation/input.go
> +}
Хорошая идея чтобы вынести разные сообщения в разные функции-печаталки. Лайк.

2024-11-15 17:56 UTC, eugenenazirov commented on business/calculator.go
> +package business
Мы никогда не называем слой бизнес-логики "бизнесом", его принято называть "сервисным" слоем, или слоем сервисов. 

Как правило любое более-менее крупное приложение будет содержать много разных пакетов с бизнес-логикой, и если мы будем называть их одинаково - service, получится неразбериха. Поэтому также популярен подход из DDD, где мы именуем пакеты по названию доменных сущностей которые они обслуживают. У тебя пока нет доменных сущностей, но уже есть вполне сформировавшийся набор операций - вычисления. Предлагаю так и назвать этот пакет: `calculations`. В будущем ты еще оценишь преимущества такого названия.

С сервисами разберемся позже, когда копнем в чистую архитектуру глубже. Пока просто `calculations` вполне достаточно.

2024-11-15 17:56 UTC, eugenenazirov commented on business/calculator.go
> +
Nit: лишний line-break.

2024-11-16 13:32 UTC, igorstupnik commented on my_calc_v2.go
он был в main, теперь я создал ветку obsolete_files  и поместил его туда, а в main удалил

2024-11-16 13:38 UTC, igorstupnik commented on presentation/input.go
> +//presentation/input.go
удалил добавил коммит

2024-11-16 13:50 UTC, igorstupnik commented on presentation/input.go
> +package presentation
переименовал в console, сделал коммит

2024-11-16 14:20 UTC, igorstupnik commented on business/calculator.go
> +package business
переименовал business в calculations залил коммито. Отдельным коммитом залил изменнения в коде.

2024-11-16 14:21 UTC, igorstupnik commented on business/calculator.go
> +
не ясно в 25 строке?

2024-11-16 15:37 UTC, eugenenazirov commented on my_calc_v2.go
Ок. Если что, рекомендую сохранять проект по версиям. Читай подробнее про [семантическое версионирование здесь ](https://wiki.merionet.ru/articles/chto-takoe-semanticheskoe-versionirovanie)(и не стесняйся гуглить другие источники).

2024-11-16 15:37 UTC, eugenenazirov commented on business/calculator.go
> +
Да

2024-11-16 15:39 UTC, eugenenazirov approved these changes
Отлично. На этом этапе все хорошо. Почитай оставшиеся комменты и переходи к go-project-layout.

2024-11-17 07:53 UTC, merged