add logger
igorstupnik/for_git pull request #6
Opened 2024-11-22 15:17 UTC by igorstupnik

Hi there could you please look at the logger

2024-11-22 15:30 UTC, eugenenazirov requested changes

2024-11-25 08:01 UTC, eugenenazirov requested changes
В целом так уже получше, но давай все-таки переключимся на один из сторонних пакетов, про которые говорил ранее, так наверяка будет понятнее чем сейчас ты мучаешься со стандартным логгером)

2024-11-28 04:29 UTC, eugenenazirov requested changes
Уже намного лучше. Теперь выглядит внятно. Главная проблема пока еще все та же - глобальная переменная.

2024-11-28 04:29 UTC, eugenenazirov commented on pkg/logger/logger.go
> +var Log *logrus.Logger
Все еще не избавились от глобальной переменной. Напоминаю)

2024-11-28 04:29 UTC, eugenenazirov commented on pkg/logger/logger.go
> +func Init() {
Вот эта штука как раз должна не присваивать логгер в глобальную переменную, а возвращать его инстанс, чтобы потом использовать его во всем приложении, путём Dependency Injection.

2024-12-03 11:47 UTC, eugenenazirov requested changes
В целом идею ты уловил. Можно всякие мелочи поправить.

2024-12-03 11:47 UTC, eugenenazirov commented on pkg/calculations/calculator.go
> +
Nit: лишний line-break

2024-12-03 11:47 UTC, eugenenazirov commented on cmd/cli/main.go
> +	result, err := calculations.Calculate(a, b, operator, log)
Nit: если функция принимает зависимости, обычно они идут первыми в списке аргументов, а уже затем аргументы относящиеся к БЛ. Но это вообще не критично, в любом случае мы будем переписывать на другой подход.

2024-12-03 11:47 UTC, eugenenazirov commented on pkg/calculations/calculator.go
> +	}).Info("Calculation in prosess")
Nit: наверное все же 'in progress' ну или хотя бы просто 'Calculation processing'.

2024-12-03 11:47 UTC, eugenenazirov commented on pkg/calculations/calculator.go
> +		log.WithError(err).Error("Error: invalid operator")
Nit: дублировать слово Error не имеет смысла, так как твой уровень логгирования итак Error.

2024-12-03 11:47 UTC, eugenenazirov commented on internal/console/input.go
> +	log.WithField("Error", err).Info("The error has displayed successfully")
1. Такие логи лучше делать с уровнем Debug, если они действительно нужны. 
2. Как правило они не нужны, так как ты по-любому увидишь в консоли, если что-то напечаталось))
3. Если уж что-то произошло успешно, надо логгировать это ПОСЛЕ того как оно произошло, сейчас же может возникнуть ситуация что лог будет напечатан, а вывод в консоль упадет с ошибкой/паникой. Получается мы наврали в логах?)

2024-12-06 11:05 UTC, igorstupnik commented on cmd/cli/main.go
> +	result, err := calculations.Calculate(a, b, operator, log)
это тогда не буду переделывать

2024-12-06 11:06 UTC, igorstupnik commented on pkg/calculations/calculator.go
> +	}).Info("Calculation in prosess")
done

2024-12-06 11:06 UTC, igorstupnik commented on pkg/calculations/calculator.go
> +		log.WithError(err).Error("Error: invalid operator")
done

2024-12-06 11:06 UTC, igorstupnik commented on internal/console/input.go
> +	log.WithField("Error", err).Info("The error has displayed successfully")
done

2024-12-06 11:54 UTC, eugenenazirov approved these changes
Все ок. Можешь двигаться дальше.

2024-12-06 12:43 UTC, merged